language: java
before_install:
- openssl aes-256-cbc -K $encrypted_1d0ce918109b_key -iv $encrypted_1d0ce918109b_iv
  -in client-secret.json.enc -out client-secret.json -d
- cd $HOME && wget --quiet https://storage.googleapis.com/appengine-sdks/featured/appengine-java-sdk-1.9.74.zip
  && unzip -q appengine-java-sdk-1.9.74.zip && cd ${TRAVIS_BUILD_DIR};
env: PATH=${HOME}/appengine-java-sdk-1.9.74/bin:${PATH} VERSION="$(date +%Y%m%dt%H%M%S)g$(git
  rev-parse --short HEAD)"
deploy:
  skip_cleanup: true
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
